// Phase 6: Multi-harness install — Claude Code, Codex, OpenCode.
// Interactive `deepindex install` prompts the user to choose harness(es).

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { load as yamlLoad, dump as yamlDump } from 'js-yaml';
import { installClaudeSettings } from './mcp/install.js';

export type Harness = 'claude-code' | 'codex' | 'opencode' | 'deepseek-harness';

export interface InstallResult {
  harness: Harness;
  path: string;
  ok: boolean;
  message: string;
}

// --- Codex ---

/** Codex hooks.json — same events as Claude Code, different config shape. */
function codexHooksJson(): string {
  const hook = (command: string, matcher?: string) => ({
    hooks: [{ type: 'command', command }],
    ...(matcher ? { matcher } : {}),
  });
  return JSON.stringify(
    {
      hooks: {
        SessionStart: [hook('deepindex hook session-start', 'startup|resume')],
        UserPromptSubmit: [hook('deepindex hook user-prompt-submit')],
        PostToolUse: [hook('deepindex hook post-tool-use')],
        SessionEnd: [hook('deepindex hook session-end')],
      },
    },
    null,
    2
  ) + '\n';
}

/** Codex config.toml — MCP server registration. */
function codexConfigToml(): string {
  return `[mcp_servers.deepindex]
command = "deepindex"
args = ["mcp", "serve"]
`;
}

/** Install DeepIndex into a Codex project: .codex/hooks.json + config.toml. */
export function installCodex(projectRoot: string): InstallResult {
  const codexDir = join(projectRoot, '.codex');
  mkdirSync(codexDir, { recursive: true });
  const hooksPath = join(codexDir, 'hooks.json');
  const configPath = join(codexDir, 'config.toml');
  writeFileSync(hooksPath, codexHooksJson());
  // Merge MCP server into existing config.toml if present (additive).
  if (existsSync(configPath)) {
    const existing = readFileSync(configPath, 'utf8');
    if (!existing.includes('[mcp_servers.deepindex]')) {
      writeFileSync(configPath, existing + '\n' + codexConfigToml());
    }
  } else {
    writeFileSync(configPath, codexConfigToml());
  }
  return { harness: 'codex', path: hooksPath, ok: true, message: `installed Codex hooks + MCP into ${codexDir}` };
}

// --- OpenCode ---

/** OpenCode plugin — TS file OpenCode loads from .opencode/plugins/. Subscribes
 *  to events and calls the deepindex CLI. */
function openCodePluginSource(): string {
  return `// DeepIndex OpenCode plugin — auto-generated by \`deepindex install\`.
// Syncs git history on session start and captures tool use.
import { Plugin } from "@opencode-ai/plugin";
import { execSync } from "node:child_process";

const run = (args: string[]) => {
  try {
    execSync("deepindex " + args.join(" "), { stdio: "ignore" });
  } catch {
    // deepindex not installed or repo not indexed — non-fatal.
  }
};

export const DeepIndexPlugin: Plugin = async (ctx) => ({
  event: async ({ event }) => {
    switch (event.type) {
      case "session.created":
        run(["hook", "session-start"]);
        break;
      case "file.edited":
        run(["hook", "post-tool-use", "--tool", "edit"]);
        break;
      case "session.status":
        if (event.properties.status?.type === "idle") {
          run(["hook", "session-end", "--session", event.properties.sessionID]);
        }
        break;
    }
  },
});
`;
}

/** Install DeepIndex into an OpenCode project: .opencode/plugins/deepindex/index.ts. */
export function installOpenCode(projectRoot: string): InstallResult {
  const pluginDir = join(projectRoot, '.opencode', 'plugins', 'deepindex');
  mkdirSync(pluginDir, { recursive: true });
  const path = join(pluginDir, 'index.ts');
  writeFileSync(path, openCodePluginSource());
  return { harness: 'opencode', path, ok: true, message: `installed OpenCode plugin into ${pluginDir}` };
}

// --- DeepSeek Harness (DSH) ---

/** DSH MCP client entry for the deepindex server. */
function dshMcpEntry(): Record<string, unknown> {
  return {
    id: 'mcp-deepindex',
    name: '@deepseek-ai/dsh-mcp-client',
    config: {
      serverName: 'deepindex',
      transport: 'stdio',
      command: 'deepindex',
      args: ['mcp', 'serve'],
    },
  };
}

/** Default DSH global config path. */
export function defaultDshConfigPath(): string {
  return join(homedir(), '.dsh', 'cordis.patch.yml');
}

/** Install DeepIndex into the DeepSeek Harness: add a dsh-mcp-client entry to
 *  the DSH cordis.patch.yml (additive merge, no duplicates). */
export function installDsh(configPath = defaultDshConfigPath()): InstallResult {
  const dir = join(configPath, '..');
  mkdirSync(dir, { recursive: true });
  let entries: unknown[] = [];
  if (existsSync(configPath)) {
    try {
      const parsed = yamlLoad(readFileSync(configPath, 'utf8'));
      if (Array.isArray(parsed)) entries = parsed;
    } catch {
      entries = [];
    }
  }
  const exists = entries.some(
    (e) => typeof e === 'object' && e !== null && (e as { id?: string }).id === 'mcp-deepindex'
  );
  if (!exists) {
    entries.push(dshMcpEntry());
    writeFileSync(configPath, yamlDump(entries, { lineWidth: 120 }) + '\n');
  }
  return {
    harness: 'deepseek-harness',
    path: configPath,
    ok: true,
    message: exists
      ? `DeepSeek Harness MCP already configured in ${configPath}`
      : `installed DeepSeek Harness MCP into ${configPath}`,
  };
}

// --- Interactive install ---

/** Install for a single harness. */
export function installHarness(projectRoot: string, harness: Harness): InstallResult {
  switch (harness) {
    case 'claude-code': {
      const r = installClaudeSettings(projectRoot);
      return { harness, path: r.path, ok: true, message: `installed Claude Code MCP + hooks into ${r.path}` };
    }
    case 'codex':
      return installCodex(projectRoot);
    case 'opencode':
      return installOpenCode(projectRoot);
    case 'deepseek-harness':
      return installDsh();
  }
}

/** Interactive install: prompt the user to choose harness(es). */
export async function installInteractive(projectRoot: string): Promise<InstallResult[]> {
  const { createInterface } = await import('node:readline/promises');
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const results: InstallResult[] = [];
  try {
    const answer = await rl.question(
      'Which AI harness(es) to install DeepIndex for?\n' +
        '  1) Claude Code\n' +
        '  2) Codex\n' +
        '  3) OpenCode\n' +
        '  4) DeepSeek Harness\n' +
        '  5) All\n' +
        'Enter numbers (comma-separated, e.g. "1,2"): '
    );
    const choices = answer
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean);
    const selected = new Set<Harness>();
    for (const c of choices) {
      if (c === '5' || c.toLowerCase() === 'all') {
        selected.add('claude-code');
        selected.add('codex');
        selected.add('opencode');
        selected.add('deepseek-harness');
      } else if (c === '1') selected.add('claude-code');
      else if (c === '2') selected.add('codex');
      else if (c === '3') selected.add('opencode');
      else if (c === '4') selected.add('deepseek-harness');
    }
    for (const h of selected) {
      results.push(installHarness(projectRoot, h));
    }
  } finally {
    rl.close();
  }
  return results;
}
